import {
  Activity,
  Archive,
  Bot,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  CircleStop,
  Command,
  FileDiff,
  FileText,
  FolderOpen,
  FolderPlus,
  GitBranch,
  History,
  Image,
  Library,
  LayoutDashboard,
  MessageSquare,
  Moon,
  Paperclip,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trash2,
  Users,
  X
} from "lucide-react";

export const icons = {
  activity: Activity,
  archive: Archive,
  bot: Bot,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "circle-help": CircleHelp,
  "circle-stop": CircleStop,
  command: Command,
  "file-diff": FileDiff,
  "file-text": FileText,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  "git-branch": GitBranch,
  history: History,
  image: Image,
  library: Library,
  "layout-dashboard": LayoutDashboard,
  "message-square": MessageSquare,
  moon: Moon,
  paperclip: Paperclip,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  "panel-right-close": PanelRightClose,
  "panel-right-open": PanelRightOpen,
  plus: Plus,
  refresh: RefreshCw,
  restore: RotateCcw,
  search: Search,
  send: Send,
  settings: Settings,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  sun: Sun,
  trash: Trash2,
  users: Users,
  x: X
};

export type IconName = keyof typeof icons;
